# This is a basic workflow to help you get started with Actions

name: run-given-script


# Controls when the workflow will run
on:
 workflow_run:
    workflows: [build-artifacts]
    types:
      - completed
  
env:
  SCRIPT_TO_BE_RUN: scripts/test.py

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Download scripts
        run: |
          echo "downloading artifacts for run_id: ${{ context.payload.workflow_run.id }}"
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/karelWeingart/pythonFun/actions/runs/${{ context.payload.workflow_run.id }}/artifacts
          #docker build -t new-python-image ./docker
